FROM python:3.8.1-alpine3.11

WORKDIR /usr/src/app

COPY Pipfile Pipfile
COPY run_reporter_service.py run_reporter_service.py
COPY ci/__init__.py ci/__init__.py
COPY ci/reporter ci/reporter
COPY ci/logger.py ci/logger.py
COPY ci/utils.py ci/utils.py

RUN pip install loguru

EXPOSE ${PORT}