FROM python:3.8.1-alpine3.11

WORKDIR /usr/src/app

COPY Pipfile Pipfile
COPY run_test_runner.py run_test_runner.py
COPY ci/__init__.py ci/__init__.py
COPY ci/test_runner ci/test_runner
COPY ci/logger.py ci/logger.py
COPY ci/utils.py ci/utils.py

RUN pip install loguru

EXPOSE ${PORT}